// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3YuVU6fK6njdVCWYZs_KxB7wK7XhypE',
    appId: '1:222889111252:web:8de7321270d183ffbbd541',
    messagingSenderId: '222889111252',
    projectId: 'app-day-assign',
    authDomain: 'app-day-assign.firebaseapp.com',
    storageBucket: 'app-day-assign.appspot.com',
    measurementId: 'G-Z5L2FGZ3YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnbnh3L-r_5A-agR0vs-HtdSiCvaQuUNc',
    appId: '1:222889111252:android:2740395f734a2a2ebbd541',
    messagingSenderId: '222889111252',
    projectId: 'app-day-assign',
    storageBucket: 'app-day-assign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDHnWKsnCHNRFvyblAdOCK6HwWzBrS9o',
    appId: '1:222889111252:ios:6cbacb16b33a3dffbbd541',
    messagingSenderId: '222889111252',
    projectId: 'app-day-assign',
    storageBucket: 'app-day-assign.appspot.com',
    iosClientId: '222889111252-t8e7n1ikc10tqpuse1rfgh095okma4qp.apps.googleusercontent.com',
    iosBundleId: 'com.appdayproject.appDayProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVDHnWKsnCHNRFvyblAdOCK6HwWzBrS9o',
    appId: '1:222889111252:ios:6cbacb16b33a3dffbbd541',
    messagingSenderId: '222889111252',
    projectId: 'app-day-assign',
    storageBucket: 'app-day-assign.appspot.com',
    iosClientId: '222889111252-t8e7n1ikc10tqpuse1rfgh095okma4qp.apps.googleusercontent.com',
    iosBundleId: 'com.appdayproject.appDayProject',
  );
}
